// Path: apps/web-client/src/lib/aihire/technicalKeywords.ts

export const DEFAULT_TECHNICAL_KEYWORDS: string[] = [
  "python",
  "javascript",
  "typescript",
  "java",
  "kotlin",
  "scala",
  "c++",
  "c#",
  "go",
  "golang",
  "rust",
  "swift",
  "php",
  "ruby",
  "r",
  "matlab",
  "sql",
  "postgresql",
  "postgres",
  "mysql",
  "sqlite",
  "mongodb",
  "redis",
  "dynamodb",
  "snowflake",
  "bigquery",
  "spark",
  "hadoop",
  "pandas",
  "numpy",
  "polars",
  "scikit-learn",
  "pytorch",
  "tensorflow",
  "keras",
  "xgboost",
  "lightgbm",
  "machine learning",
  "deep learning",
  "data science",
  "artificial intelligence",
  "ai",
  "llm",
  "nlp",
  "computer vision",
  "generative ai",
  "rag",
  "embedding",
  "vector database",
  "faiss",
  "pinecone",
  "weaviate",
  "langchain",
  "llamaindex",
  "bedrock",
  "amazon nova",
  "nova act",
  "claude",
  "openai",
  "gemini",
  "react",
  "next.js",
  "nextjs",
  "node.js",
  "nodejs",
  "express",
  "nestjs",
  "hono",
  "fastapi",
  "flask",
  "django",
  "spring",
  "spring boot",
  "rest api",
  "api",
  "apis",
  "graphql",
  "grpc",
  "websocket",
  "webhook",
  "webhooks",
  "microservices",
  "docker",
  "kubernetes",
  "terraform",
  "linux",
  "bash",
  "shell scripting",
  "aws",
  "azure",
  "gcp",
  "cloud infrastructure",
  "serverless",
  "lambda",
  "ec2",
  "s3",
  "cloudformation",
  "ci/cd",
  "github actions",
  "gitlab ci",
  "jenkins",
  "git",
  "github",
  "gitlab",
  "supabase",
  "drizzle",
  "drizzle orm",
  "postgres-js",
  "trpc",
  "clerk",
  "playwright",
  "selenium",
  "puppeteer",
  "automation",
  "zapier",
  "workato",
  "make",
  "power automate",
  "airflow",
  "dbt",
  "tableau",
  "power bi",
  "looker",
  "excel",
  "vscode",
  "visual studio code",
  "json",
  "yaml",
  "xml",
  "html",
  "css",
  "tailwind",
  "typescript react",
  "full-stack",
  "frontend",
  "backend",
  "distributed systems",
  "system design",
  "testing",
  "unit testing",
  "integration testing",
  "e2e testing",
];

export function normalizeForKeywordMatch(value: string): string {
  return value.toLowerCase().replace(/\s+/g, " ").trim();
}